Feat validate area request
MarkAntipin/livechrg-api pull request #11
Opened 2024-02-10 11:54 UTC by u-cha

Hi Mark!

Please review the `get_stations_by_area` endpoint validation feature.

2024-02-12 08:49 UTC, MarkAntipin requested changes

2024-02-12 08:49 UTC, MarkAntipin commented on src/api/app.py
> +    @app.exception_handler(ValidationError)
А это точно нужно? Он автоматом этого не делает?

2024-02-12 08:49 UTC, MarkAntipin commented on src/api/routers/v1/models.py
> +    def sw_is_lower_left_than_ne(self) -> typing.Type[AreaRequest]:
А если западная точка находится "восточнее" восточной точки?)
Нужно прям чтобы ничего плохого через твою валидацию не просочилось)

2024-02-12 08:49 UTC, MarkAntipin commented on tests_functional/api/test_get_station_by_area_request_validation.py
> +async def test_get_stations_by_area__invalid_lat__returns_422(client: TestClient, pg: asyncpg.Pool) -> None:
Один функ тест - это хорошо, чтобы проверить, что возвращается 422 с нужной ошибкой.
Но я бы хотел юнит тесты на это дело. Потому что функ теты - они дорогие (долго выполняются и замедляют процесс разработки)
А тут отличный сценарий для юнитов

2024-02-12 08:52 UTC, u-cha commented on src/api/app.py
> +    @app.exception_handler(ValidationError)
нет, возвращает server error. нужно хэндлить ошибку, чтобы довести пользователю эту информацию

2024-02-12 08:57 UTC, u-cha commented on src/api/routers/v1/models.py
> +    def sw_is_lower_left_than_ne(self) -> typing.Type[AreaRequest]:
Это уже учтено здесь

` self.sw_lat <= self.ne_lat and`
 широта юга меньше или равна широте севера
`self.sw_lon <= self.ne_lon `
долгота запада меньше или равна долготе востока

Подумаю, что еще может быть, но навскидку нет, т.к. тут всего 2 точки по 2 координаты и их уже сравнили.
Ограничения по общим значением заданы выше в полях.

2024-02-15 07:24 UTC, u-cha commented on src/api/routers/v1/models.py
> +    def sw_is_lower_left_than_ne(self) -> typing.Type[AreaRequest]:
ну я не вижу больше :) буду рад если укажешь на косяк

2024-02-15 07:24 UTC, u-cha commented on tests_functional/api/test_get_station_by_area_request_validation.py
> +async def test_get_stations_by_area__invalid_lat__returns_422(client: TestClient, pg: asyncpg.Pool) -> None:
написал несколько юнитов.

2024-02-15 17:48 UTC, MarkAntipin approved these changes

2024-02-15 17:48 UTC, MarkAntipin commented on src/api/routers/v1/models.py
> +from __future__ import annotations
А это где используется?

2024-02-19 14:44 UTC, merged