Migrate post endpoint
MarkAntipin/livechrg-api pull request #14
Opened 2024-02-20 16:35 UTC by iliamunaev

Create /router/inner/stations.py + __init__.py
Migrate post endpoint to the new directory, add new prefix
Add router to app.py
Create tests

2024-02-20 19:31 UTC, MarkAntipin requested changes

2024-02-20 19:31 UTC, MarkAntipin commented on src/api/routers/inner/stations.py
> +from src.api.routers.v1.models import AddStationsRequest
кмк это нужно унести в /inner/model Теперь это моделька, которая относится к inner)

2024-02-20 19:31 UTC, MarkAntipin commented on tests_functional/api/test_post_stations.py
> +import json
Давай сделаем так:
- у нас уже есть тесты на эту ручку, не вижу смысла в новых
- такой параметрайз не очень хорош, он очень большой и там ничего не понятно.
- Предлагаю вместо твоего файла проапдейтить вот этот файл: https://github.com/MarkAntipin/livechrg-api/blob/master/tests_functional/api/test_add_stations.py
там можно передавать через параметрайз только урл, у нас 2 варианта: `/inner/api/stations` и `/api/v1/stations`

2024-02-21 09:44 UTC, iliamunaev commented on src/api/routers/inner/stations.py
> +from src.api.routers.v1.models import AddStationsRequest
Перенес те модели, котрые относятся к inner

2024-02-21 09:47 UTC, iliamunaev commented on tests_functional/api/test_post_stations.py
> +import json
Чтобы не хардкодить и не копировать условние parametrize переде  каждой тест-функцией, создал класс TestClass.

2024-02-21 10:33 UTC, MarkAntipin requested changes

2024-02-21 10:33 UTC, MarkAntipin commented on tests_functional/api/test_add_stations.py
> +class TestClass:
Это зачем?)

2024-02-21 10:39 UTC, iliamunaev commented on tests_functional/api/test_add_stations.py
> +class TestClass:
Иначе @pytest.mark.parametrize работает только с первой тестовой функцикцей. Один из вариантов - убрать класс и добавить @pytest.mark.parametrize перед каждой фуекцией.

2024-02-21 11:07 UTC, MarkAntipin approved these changes

2024-02-21 11:09 UTC, merged