Refactoring and validation for parameter limit of handle get stations by area
MarkAntipin/livechrg-api pull request #8
Opened 2024-02-04 04:34 UTC by AndreyRahimov

add function _format_station
refactor methods get_by_source_and_inner_id, get_by_area
add method get_by_source_and_inner_id to StationsRepository
add validation for parameter limit of handle get stations by area
minor fixes

2024-02-05 07:37 UTC, MarkAntipin requested changes

2024-02-05 07:37 UTC, MarkAntipin commented on src/api/routers/v1/stations.py
> +        station_source: str,
А почему это убрал?

2024-02-05 07:37 UTC, MarkAntipin commented on src/repositories/postgres/stations.py
> +            row = rows[0]
а почему не обрабатываешь?
Там может ничего не быть, а ты берешь индекс?

2024-02-05 07:37 UTC, MarkAntipin commented on src/services/stations.py
> +        coordinates = json.loads(station_row['coordinates'])
давай это вынесем, я хочу, чтобы _format_station только собирал объект стации, а не делал запросы в базу данных

2024-02-05 08:19 UTC, AndreyRahimov commented on src/api/routers/v1/stations.py
> +        station_source: str,
get_station_by_source_and_inner_id внутри себя передаёт station_source в метод stations_service.get_by_source_and_inner_id, который работает со str. В соответствии с этим исправил тип в аннотации.

2024-02-05 08:33 UTC, AndreyRahimov commented on src/repositories/postgres/stations.py
> +            row = rows[0]
Исправил, и это решило ошибку, которая у меня выбрасывалась в новом методе get_by_source_and_inner_id

2024-02-06 18:37 UTC, MarkAntipin requested changes

2024-02-06 18:37 UTC, MarkAntipin commented on src/api/routers/v1/stations.py
> +        station_source: str,
Верни назад, пожалуйста) Это нужно, чтобы в доке был выбор, какую строку можно подставить. 

<img width="497" alt="Screenshot 2024-02-06 at 19 31 52" src="https://github.com/MarkAntipin/livechrg-api/assets/44891461/c3378d3a-f690-46f2-a114-9f9367731c45">


Ты можешь передать в функу .value от енумки, чтобы было по тайпингу

2024-02-06 18:37 UTC, MarkAntipin commented on src/services/stations.py
> +    async def _format_station(
А почему она async?

2024-02-06 18:37 UTC, MarkAntipin commented on src/services/stations.py
> +            station = await self._format_station(
Если уберешь async, не забудь убрать и await

2024-02-06 18:37 UTC, MarkAntipin commented on tests_functional/api/test_get_stations_by_area.py
> +async def test_get_stations_by_area__validation_for_limit(client: TestClient, pg: asyncpg.Pool) -> None:
👍

2024-02-06 18:37 UTC, MarkAntipin commented on src/services/stations.py
> +        comments_rows = comment_rows_by_station_id.get(station_id, [])
Смотри тут commentS_rows а выше comment_rows_by_station_id (без S) сделай кк хочешь, но хочется, чтобы это было единообразно)

2024-02-09 11:03 UTC, closed without merging